### ISSUE TITLE
How to open/configure module?

### ISSUE THREAD

**Issue by whitewallman** [AsyJAIZ/Notification-Shade-Transparency#12]
Installed APK and activated in lsposed but don't see app to turn module on or configure. Please advise.

**Comment by e-t-l** [comment]
Same. Does it have to be enabled for certain apps in the LSposed module manager in order to work? I enabled it for System UI because that said "recommended" but I don't know if there's something else that needs to be enabled too. The notification shade doesn't look any different.

**Comment by AsyJAIZ** [comment]
No. Otherwise it would be described. You should _always_ check logs if you’re going to open an issue here. Also, I don’t have a suitable device nor time to keep working on this project, so it’s kinda on a hiatus. Just wait for a fix, I’ll try to post a new release soon.
