### ISSUE TITLE
Add recent task mask transparency

### ISSUE THREAD

**Issue by StarVase** [AsyJAIZ/Notification-Shade-Transparency#13]
Hello, I found this a wonderful project and I like it a lot. What about a
make Recent Task ui's mask transparency and it will be a bettet project.
Thank you.![Screenshot_20241002-090526_GitHub.png](https://github.com/user-attachments/assets/5955e0d1-c963-4702-905d-cf25157b0612)

**Comment by ppebb** [comment]
If your launcher supports it, this is also a feature in https://github.com/skittles9823/QuickSwitch. Since you're using lsposed I assume you also have a way to use magisk modules.

**Comment by StarVase** [comment]
> If your launcher supports it, this is also a feature in https://github.com/skittles9823/QuickSwitch. Since you're using lsposed I assume you also have a way to use magisk modules.

Thanks a lot, I'll have a try!!!

**Comment by StarVase** [comment]
> If your launcher supports it, this is also a feature in https://github.com/skittles9823/QuickSwitch. Since you're using lsposed I assume you also have a way to use magisk modules.

However, currently I'm using pixel launcher and lt seems not support transparent recent task mask.
