### ISSUE TITLE
Doesn`t work on Evolution X (A13)

### ISSUE THREAD

**Issue by ilovefurnaces** [AsyJAIZ/Notification-Shade-Transparency#2]
Device: Xiaomi Redmi Note 9S (miatoll or curtana)

(sorry for non english)
![Screenshot_20230319-135112_Оболочка](https://user-images.githubusercontent.com/80579326/226167152-f7070f48-7233-4fb1-991c-99c780386823.png)
![Screenshot_20230319-135100_Chrome](https://user-images.githubusercontent.com/80579326/226167153-f28013fb-01a5-47a3-96e4-399b0e9f0097.png)

**Comment by AsyJAIZ** [comment]
Привет, возможно сегодня я выпущу фикс
