### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [AsyJAIZ/Notification-Shade-Transparency#3]
Thanks for making your module available including its source! Could you please state what license it falls under, to (hopefully) make it fully FOSS? Thanks in advance!

**Comment by IzzySoft** [comment]
No opinion, @AsyJAIZ ?

**Comment by AsyJAIZ** [comment]
nah @IzzySoft

**Comment by IzzySoft** [comment]
Thanks for "nah" instead of "no" :rofl: In return, your module becomes [available here](https://apt.izzysoft.de/packages/com.asyjaiz.A12blur/) at around 6 pm UTC (as it now meets all criteria for that). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. And if you'd have an icon to add, I gladly put that up here then, too.
