### ISSUE TITLE
How do I get this working?

### ISSUE THREAD

**Issue by DoubleDTech23** [AsyJAIZ/Notification-Shade-Transparency#8]
I am fairly new to modules and LSPatch. I have managed to set LSPatch up with Shizuku on my Android 13 device, and I've also installed this module. LSPatch recognises it, as it shows up in the application in Manage > Modules.

What do I do from here?

**Comment by AsyJAIZ** [comment]
Well, it shows up, so why don’t you turn it on?

I, however, cannot guarantee the module to work with LSPatch because of the way it works.

**Comment by DoubleDTech23** [comment]
This is all that shows up:

![Screenshot_20231121-073048.png](https://github.com/AsyJAIZ/Notification-Shade-Transparency/assets/141555777/03d89ad7-3490-4d79-8d8c-0da408d97c9f)

I don't know how to turn it on.

**Comment by AsyJAIZ** [comment]
Have you tried clicking on it?

**Comment by DoubleDTech23** [comment]
Yes, I've tried that.

**Comment by AsyJAIZ** [comment]
Have you tried checking SystemUI on the Apps section?

**Comment by JuanCarrlosJacome** [comment]
I don't know how to get it to work either, it's already turned on in SLPosed but it's not working

**Comment by DoubleDTech23** [comment]
> I don't know how to get it to work either, it's already turned on in SLPosed but it's not working 

Is this the only module that doesn't work for you? 

I can't figure out how to use any modules.

**Comment by AsyJAIZ** [comment]
> I can't figure out how to use any modules.

Well, LSPatch patches the app that you have the modules to install for. Since System UI is a **system** app/service, it can't be patched, so i suppose no LSPatch support.



> I don't know how to get it to work either, it's already turned on in SLPosed but it's not working

Check your logs. Check module scope. Be sure to have System UI turned on (it will be recommended). If you have any other questions, make a new issue.

**Comment by JuanCarrlosJacome** [comment]
> > I don't know how to get it to work either, it's already turned on in SLPosed but it's not working
> 
> Is this the only module that doesn't work for you?
> 
> I can't figure out how to use any modules.

I'm using disable flag secure and geergit with no problem

**Comment by DoubleDTech23** [comment]
What's that?

**Comment by JuanCarrlosJacome** [comment]
The fist one allows you to make screenshots and screen recording in apps that won't allow you, the second one is for changing the "fingerprint" of your phone for different apps IMEI and stuff like that, so your apps are not tracking your every move

**Comment by DoubleDTech23** [comment]
I've managed to set up the disable flag secure by integrating the module into the application that blocks screenshots.

What app am I supposed to integrate this notification shade transparency module to?

**Comment by AsyJAIZ** [comment]
> System UI is a **system** app/service, it can't be patched, so **no** LSPatch support.



> > I don't know how to get it to work either, it's already turned on in SLPosed but it's not working
> 
> **Check your logs.** Check module scope. make a **new issue**.

Do i have to repeat this all the time? I don’t. And i won’t. You can react with as much dislikes as you’d like. Every single module developer for LSPosed/LSPatch will tell you to check every single thing. I’m always willing to help, but i don’t have enough information to do that. **No logs means no bugs.** I haven’t seen any evidences of the module misbehaving.

Additionally, if it doesn’t work, that may mean that you have some OEM ROM on your device OR that the code was changed by the maintainer of your specific custom ROM.
Only AOSP-based ROMs are supported.

If you have an AOSP-based ROM and compatible Android version - **check your logs**! Wanna figure them out? Post them here.

**Comment by DoubleDTech23** [comment]
Does this need root?

**Comment by AsyJAIZ** [comment]
LSPosed requires Magisk, so technically yes

**Comment by DoubleDTech23** [comment]
So it doesn't support LSPatch

**Comment by AsyJAIZ** [comment]
Just as i said,
> no LSPatch support.
